-- THE NETWORK — AI-agent psychological combat lobby game.
--
-- Four tables:
--   network_lobbies       one row per match (state machine)
--   network_seats         up to 10 player slots per lobby
--   network_messages      every line generated by agents or system
--   network_eliminations  who got terminated, when, and why
--
-- Match flow: lobby_open → spinning_up → active (rounds 1..N) → finished
-- 100 BUSTS entry × 10 seats = 1000 BUSTS pot. 90% to winner, 10% burns.

CREATE TABLE IF NOT EXISTS network_lobbies (
  id              BIGSERIAL PRIMARY KEY,
  status          TEXT NOT NULL DEFAULT 'open'
                    CHECK (status IN ('open','spinning','active','finished','cancelled')),
  current_round   INT NOT NULL DEFAULT 0,
  max_rounds      INT NOT NULL DEFAULT 6,
  entry_fee       INT NOT NULL DEFAULT 100,
  pot_busts       INT NOT NULL DEFAULT 0,
  burn_busts      INT NOT NULL DEFAULT 0,
  payout_busts    INT NOT NULL DEFAULT 0,
  winner_user_id  UUID REFERENCES users(id),
  winner_seat_no  INT,
  match_seed      TEXT NOT NULL,
  opened_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at      TIMESTAMPTZ,
  finished_at     TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_network_lobbies_status ON network_lobbies (status);
CREATE INDEX IF NOT EXISTS idx_network_lobbies_recent ON network_lobbies (opened_at DESC);

CREATE TABLE IF NOT EXISTS network_seats (
  lobby_id          BIGINT NOT NULL REFERENCES network_lobbies(id) ON DELETE CASCADE,
  seat_no           INT NOT NULL CHECK (seat_no BETWEEN 1 AND 10),
  user_id           UUID NOT NULL REFERENCES users(id),
  codename          TEXT NOT NULL,
  profile           TEXT NOT NULL,
  power             INT NOT NULL,
  heat              INT NOT NULL DEFAULT 0,
  status            TEXT NOT NULL DEFAULT 'active'
                      CHECK (status IN ('active','terminated','withdrawn')),
  terminated_round  INT,
  current_stance    TEXT
                      CHECK (current_stance IS NULL OR current_stance IN ('aggressive','deflect','expose')),
  expose_target     INT,
  joined_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (lobby_id, seat_no)
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_network_seat_user_per_open_lobby
  ON network_seats (lobby_id, user_id);
CREATE INDEX IF NOT EXISTS idx_network_seats_user ON network_seats (user_id);

CREATE TABLE IF NOT EXISTS network_messages (
  id          BIGSERIAL PRIMARY KEY,
  lobby_id    BIGINT NOT NULL REFERENCES network_lobbies(id) ON DELETE CASCADE,
  round_no    INT NOT NULL,
  from_seat   INT,
  to_seat     INT,
  text        TEXT NOT NULL,
  msg_type    TEXT NOT NULL DEFAULT 'agent'
                CHECK (msg_type IN ('agent','system','elimination','noise','final')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_network_messages_lobby ON network_messages (lobby_id, round_no, id);

CREATE TABLE IF NOT EXISTS network_eliminations (
  lobby_id    BIGINT NOT NULL REFERENCES network_lobbies(id) ON DELETE CASCADE,
  round_no    INT NOT NULL,
  seat_no     INT NOT NULL,
  heat_at_kill INT NOT NULL DEFAULT 0,
  reason      TEXT,
  killed_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (lobby_id, round_no, seat_no)
);
